### ISSUE TITLE
frase <search> more usable

### ISSUE THREAD

**Issue by JavierLuna** [jenarvaezg/cunhaobot#7]
It could search your phrase without the frase part, only <search>

**Comment by jenarvaezg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hacer que "frase" no sea obligatorio a la hora de buscar](https://trello.com/c/Fn3zbx3w/11-hacer-que-frase-no-sea-obligatorio-a-la-hora-de-buscar)

**Comment by jenarvaezg** [comment]
I will give it a look, I could let @cunhaobot <X> work as @cunhaobot frase <X>, but that would remove the "No sabes como usarme" result, which might be useful for new users

**Comment by jenarvaezg** [comment]
This is up now. I am leaving the choice to still use "frase" in order to not break current UX
